{
 "title": "Tracestore benchmarking",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Spans / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tracestore_receiver_accepted_spans[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tracestore_receiver_refused_spans[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Traces / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tracestore_ingester_traces_created_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Spans / s / core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tracestore_receiver_accepted_spans[$__rate_interval])) / \nsum(rate(container_cpu_usage_seconds_total{image=~\".*tracestore.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cpu Usage per container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image=~\".*tracestore.*\"}[$__rate_interval])) by (name)"
    }
   ]
  },
  {
   "title": "Working set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image=~\".*tracestore.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC duration p50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{instance=~\"(ing|dist).*\", quantile=\"0.5\"}[$__rate_interval])"
    }
   ]
  }
 ]
}