apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
- name: Tracestore-a
  type: tracestore
  access: proxy
  orgId: 1
  url: http://query-frontend-a:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tracestore-a
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
- name: Tracestore-b
  type: tracestore
  access: proxy
  orgId: 1
  url: http://query-frontend-b:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tracestore-b
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
