---
global:
  clusterDomain: 'cluster.local'
gateway:
  enabled: true
minio:
  enabled: true
storage:
  trace:
    backend: s3
    s3:
      access_key: 'acme-tracestore'
      secret_key: 'supersecret'
      bucket: 'tracestore-traces'
      endpoint: 'tracestore-minio:9000'
      insecure: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
distributor:
  config:
    log_received_spans:
      enabled: true
