FROM golang:alpine AS build-dlv

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:3.16 as certs
RUN apk --update add ca-certificates bash
ARG TARGETARCH
COPY bin/linux/tracestore-${TARGETARCH} /tracestore

COPY --from=build-dlv /go/bin/dlv /dlv
COPY /cmd/tracestore/entrypoint-debug.sh /entrypoint-debug.sh
EXPOSE 2345
ENTRYPOINT [ "/entrypoint-debug.sh" ]
CMD []
